import * as z from "zod";


export const CustomPropertiesSchema = z.object({
});
export type CustomProperties = z.infer<typeof CustomPropertiesSchema>;

export const LicenseSchema = z.object({
    "key": z.string().optional(),
    "name": z.string().optional(),
    "spdx_id": z.string().optional(),
    "url": z.string().optional(),
    "node_id": z.string().optional(),
});
export type License = z.infer<typeof LicenseSchema>;

export const OrganizationSchema = z.object({
    "login": z.string().optional(),
    "id": z.number().optional(),
    "node_id": z.string().optional(),
    "avatar_url": z.string().optional(),
    "gravatar_id": z.string().optional(),
    "url": z.string().optional(),
    "html_url": z.string().optional(),
    "followers_url": z.string().optional(),
    "following_url": z.string().optional(),
    "gists_url": z.string().optional(),
    "starred_url": z.string().optional(),
    "subscriptions_url": z.string().optional(),
    "organizations_url": z.string().optional(),
    "repos_url": z.string().optional(),
    "events_url": z.string().optional(),
    "received_events_url": z.string().optional(),
    "type": z.string().optional(),
    "user_view_type": z.string().optional(),
    "site_admin": z.boolean().optional(),
});
export type Organization = z.infer<typeof OrganizationSchema>;

export const PermissionsSchema = z.object({
    "admin": z.boolean().optional(),
    "maintain": z.boolean().optional(),
    "push": z.boolean().optional(),
    "triage": z.boolean().optional(),
    "pull": z.boolean().optional(),
});
export type Permissions = z.infer<typeof PermissionsSchema>;

export const DetailResponseSchema = z.object({
    "id": z.number().optional(),
    "node_id": z.string().optional(),
    "name": z.string().optional(),
    "full_name": z.string().optional(),
    "private": z.boolean().optional(),
    "owner": OrganizationSchema.optional(),
    "html_url": z.string().optional(),
    "description": z.string().optional(),
    "fork": z.boolean().optional(),
    "url": z.string().optional(),
    "forks_url": z.string().optional(),
    "keys_url": z.string().optional(),
    "collaborators_url": z.string().optional(),
    "teams_url": z.string().optional(),
    "hooks_url": z.string().optional(),
    "issue_events_url": z.string().optional(),
    "events_url": z.string().optional(),
    "assignees_url": z.string().optional(),
    "branches_url": z.string().optional(),
    "tags_url": z.string().optional(),
    "blobs_url": z.string().optional(),
    "git_tags_url": z.string().optional(),
    "git_refs_url": z.string().optional(),
    "trees_url": z.string().optional(),
    "statuses_url": z.string().optional(),
    "languages_url": z.string().optional(),
    "stargazers_url": z.string().optional(),
    "contributors_url": z.string().optional(),
    "subscribers_url": z.string().optional(),
    "subscription_url": z.string().optional(),
    "commits_url": z.string().optional(),
    "git_commits_url": z.string().optional(),
    "comments_url": z.string().optional(),
    "issue_comment_url": z.string().optional(),
    "contents_url": z.string().optional(),
    "compare_url": z.string().optional(),
    "merges_url": z.string().optional(),
    "archive_url": z.string().optional(),
    "downloads_url": z.string().optional(),
    "issues_url": z.string().optional(),
    "pulls_url": z.string().optional(),
    "milestones_url": z.string().optional(),
    "notifications_url": z.string().optional(),
    "labels_url": z.string().optional(),
    "releases_url": z.string().optional(),
    "deployments_url": z.string().optional(),
    "created_at": z.coerce.date().optional(),
    "updated_at": z.coerce.date().optional(),
    "pushed_at": z.coerce.date().optional(),
    "git_url": z.string().optional(),
    "ssh_url": z.string().optional(),
    "clone_url": z.string().optional(),
    "svn_url": z.string().optional(),
    "homepage": z.string().optional(),
    "size": z.number().optional(),
    "stargazers_count": z.number().optional(),
    "watchers_count": z.number().optional(),
    "language": z.string().optional(),
    "has_issues": z.boolean().optional(),
    "has_projects": z.boolean().optional(),
    "has_downloads": z.boolean().optional(),
    "has_wiki": z.boolean().optional(),
    "has_pages": z.boolean().optional(),
    "has_discussions": z.boolean().optional(),
    "forks_count": z.number().optional(),
    "mirror_url": z.null().optional(),
    "archived": z.boolean().optional(),
    "disabled": z.boolean().optional(),
    "open_issues_count": z.number().optional(),
    "license": LicenseSchema.optional(),
    "allow_forking": z.boolean().optional(),
    "is_template": z.boolean().optional(),
    "web_commit_signoff_required": z.boolean().optional(),
    "topics": z.array(z.string()).optional(),
    "visibility": z.string().optional(),
    "forks": z.number().optional(),
    "open_issues": z.number().optional(),
    "watchers": z.number().optional(),
    "default_branch": z.string().optional(),
    "permissions": PermissionsSchema.optional(),
    "custom_properties": CustomPropertiesSchema.optional(),
    "organization": OrganizationSchema.optional(),
    "network_count": z.number().optional(),
    "subscribers_count": z.number().optional(),
});
export type DetailResponse = z.infer<typeof DetailResponseSchema>;
